
camel:
  springboot:
      main-run-controller: true


spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:my-app}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true


  main:
    allow-circular-references: true
sftp:
  host: 172.30.51.54
  port: 22
  username: administrator
  #password: admin
  private-key-file: C:/tmp/key/bt.rsa
  virtualDirectory: /prova1
  

input:
   directory:
       path: //data/input

output: 
    directory:
        path: //data/output
